global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "casino-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api-server:3000"]
        labels:
          service: "api-server"
          env: "production"
